# Generated by Django 5.0 on 2023-12-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=3000)),
                ('degree', models.CharField(max_length=1000)),
                ('school', models.CharField(max_length=1000)),
                ('university', models.CharField(max_length=1000)),
                ('work', models.CharField(max_length=1000)),
                ('skills', models.TextField(max_length=1000)),
            ],
        ),
    ]
